export const VISION_SCHEMA='randstudio.vision/v1';
export const VISION_TOOLS=Object.freeze(['track','mask','background-remove','object-remove','upscale']);
export const ZERO_CREDIT_MODE=true;

export function createVisionJob(tool,{clipId=null,timeRange=null,prompt='',options={}}={}){if(!VISION_TOOLS.includes(tool))throw new Error(`Vision tool non supportato: ${tool}`);return{schema:VISION_SCHEMA,id:id(),tool,clipId,timeRange,prompt:String(prompt||''),options:structuredClone(options),status:'queued',billing:'local-zero-credit',createdAt:new Date().toISOString()}}
export class VisionProviderRegistry{constructor(){this.providers=new Map()}register(provider){if(!provider?.id||typeof provider.run!=='function')throw new Error('Vision provider non valido');if(ZERO_CREDIT_MODE&&provider.local===false)throw new Error('Modalità 0 crediti: provider remoto a consumo bloccato');this.providers.set(provider.id,provider);return this}list(){return[...this.providers.values()].map(p=>({id:p.id,name:p.name||p.id,local:p.local!==false,tools:p.tools||[]}))}async run(id,job){const p=this.providers.get(id);if(!p)throw new Error(`Vision provider non trovato: ${id}`);if(ZERO_CREDIT_MODE&&p.local===false)throw new Error('Modalità 0 crediti: provider remoto bloccato');if(Array.isArray(p.tools)&&!p.tools.includes(job.tool))throw new Error(`${p.id} non supporta ${job.tool}`);return p.run(job)}}
export class GatewayVisionProvider{constructor(endpoint,{allowRemote=false}={}){this.id='local-vision-gateway';this.name='Local AI Vision';this.endpoint=String(endpoint||'').replace(/\/$/,'');this.local=isLocalEndpoint(this.endpoint);this.tools=[...VISION_TOOLS];if(ZERO_CREDIT_MODE&&!allowRemote&&this.endpoint&&!this.local)throw new Error('Modalità 0 crediti: usa localhost/LAN per il gateway AI')}async run(job){if(!this.endpoint)throw new Error('Endpoint Vision locale non configurato');const r=await fetch(`${this.endpoint}/vision`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(job)});if(!r.ok)throw new Error(`Vision locale HTTP ${r.status}`);return r.json()}}
export function isLocalEndpoint(endpoint){try{const u=new URL(endpoint);return['localhost','127.0.0.1','::1'].includes(u.hostname)||/^10\./.test(u.hostname)||/^192\.168\./.test(u.hostname)||/^172\.(1[6-9]|2\d|3[01])\./.test(u.hostname)}catch{return false}}
export function createTrack(points=[],options={}){return{schema:'randstudio.track/v1',mode:options.mode||'point',points:(points||[]).map(p=>({t:Number(p.t)||0,x:Number(p.x)||0,y:Number(p.y)||0,scale:Number(p.scale??1),rotation:Number(p.rotation??0),confidence:Number(p.confidence??1)})).sort((a,b)=>a.t-b.t)}}
export function trackAt(track,time){const p=track?.points||[];if(!p.length)return{x:0,y:0,scale:1,rotation:0,confidence:0};if(time<=p[0].t)return{...p[0]};if(time>=p.at(-1).t)return{...p.at(-1)};for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1];if(time<=b.t){const r=(time-a.t)/Math.max(.0001,b.t-a.t);return{x:lerp(a.x,b.x,r),y:lerp(a.y,b.y,r),scale:lerp(a.scale??1,b.scale??1,r),rotation:lerp(a.rotation??0,b.rotation??0,r),confidence:Math.min(a.confidence??1,b.confidence??1),t:time}}}return{...p.at(-1)}}
export function createMask(points=[],options={}){return{schema:'randstudio.mask/v1',type:options.type||'polygon',feather:Math.max(0,Number(options.feather)||0),invert:!!options.invert,points:(points||[]).map(p=>({x:Number(p.x)||0,y:Number(p.y)||0}))}}
export function createRectMask({x=0,y=0,width=1,height=1,feather=0,invert=false}={}){return{schema:'randstudio.mask/v1',type:'rect',x:Number(x)||0,y:Number(y)||0,width:Math.max(1,Number(width)||1),height:Math.max(1,Number(height)||1),feather:Math.max(0,Number(feather)||0),invert:!!invert}}
function lerp(a,b,t){return Number(a||0)+(Number(b||0)-Number(a||0))*t}function id(){return globalThis.crypto?.randomUUID?.()||`vision-${Date.now()}-${Math.random().toString(16).slice(2)}`}

if(typeof document!=='undefined')import('./local-vision-ui.js').catch(error=>console.warn('Local Vision UI non disponibile',error));
