import{rampTimelineDuration,timelineToSource}from'./speed-ramp.js';
export const PROJECT_VERSION = 1;

export function createProject({ name = 'Nuovo progetto', width = 1920, height = 1080, fps = 30 } = {}) {
  return {version:PROJECT_VERSION,id:cryptoId(),name,width,height,fps,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),tracks:[{id:'video-1',name:'Video 1',kind:'visual',clips:[]},{id:'audio-1',name:'Audio 1',kind:'audio',clips:[]}]};
}
export const cloneProject=p=>structuredClone(p);
export function projectDuration(p){return Math.max(0,...p.tracks.flatMap(t=>t.clips.map(c=>c.end||0)))}
export function addClip(p,trackId,clip){const n=cloneProject(p),t=n.tracks.find(x=>x.id===trackId);if(!t)throw new Error(`Track non trovata: ${trackId}`);const start=Math.max(0,Number(clip.start??projectDuration(n))),sourceIn=Math.max(0,Number(clip.in??0)),sourceOut=Math.max(sourceIn+.05,Number(clip.out??clip.duration??5)),rate=Math.max(.05,Number(clip.playbackRate)||1),duration=Math.max(.05,Number(clip.duration??(clip.speedRamp?rampTimelineDuration(clip.speedRamp,sourceIn,sourceOut):(sourceOut-sourceIn)/rate)));t.clips.push({id:clip.id||cryptoId(),type:clip.type||(t.kind==='audio'?'audio':'video'),name:clip.name||'Clip',sourceId:clip.sourceId,sourceName:clip.sourceName||clip.name||'media',start,end:start+duration,in:sourceIn,out:sourceOut,volume:clip.volume??1,opacity:clip.opacity??1,playbackRate:rate,speedRamp:clip.speedRamp?structuredClone(clip.speedRamp):undefined,transform:{x:0,y:0,scale:1,rotation:0,...(clip.transform||{})},motion:clip.motion?structuredClone(clip.motion):undefined,effects:Array.isArray(clip.effects)?structuredClone(clip.effects):[],keyframes:clip.keyframes?structuredClone(clip.keyframes):{},lutSourceId:clip.lutSourceId,graphic:clip.graphic?structuredClone(clip.graphic):undefined,caption:clip.caption?structuredClone(clip.caption):undefined,effectPreset:clip.effectPreset,transitionIn:clip.transitionIn?structuredClone(clip.transitionIn):undefined,transitionOut:clip.transitionOut?structuredClone(clip.transitionOut):undefined,audio:clip.audio?structuredClone(clip.audio):undefined,track:clip.track?structuredClone(clip.track):undefined,mask:clip.mask?structuredClone(clip.mask):undefined,kinetic:clip.kinetic?structuredClone(clip.kinetic):undefined});t.clips.sort((a,b)=>a.start-b.start);touch(n);return n}
export function moveClip(p,trackId,clipId,start){const n=cloneProject(p),c=requireClip(n,trackId,clipId),d=c.end-c.start;c.start=Math.max(0,Number(start));c.end=c.start+d;touch(n);return n}
export function trimClip(p,trackId,clipId,{inPoint,outPoint}){const n=cloneProject(p),c=requireClip(n,trackId,clipId),a=Math.max(0,Number(inPoint??c.in)),b=Math.max(a+.05,Number(outPoint??c.out));c.in=a;c.out=b;c.end=c.start+(c.speedRamp?rampTimelineDuration(c.speedRamp,a,b):(b-a)/Math.max(.05,c.playbackRate||1));touch(n);return n}
export function splitClip(p,trackId,clipId,time){const n=cloneProject(p),t=n.tracks.find(x=>x.id===trackId);if(!t)throw new Error(`Track non trovata: ${trackId}`);const i=t.clips.findIndex(x=>x.id===clipId);if(i<0)throw new Error(`Clip non trovata: ${clipId}`);const c=t.clips[i],v=Number(time);if(v<=c.start||v>=c.end)return n;const sourceSplit=c.speedRamp?timelineToSource(c.speedRamp,c.in,c.out,v-c.start):c.in+(v-c.start)*Math.max(.05,c.playbackRate||1),left={...structuredClone(c),end:v,out:sourceSplit},right={...structuredClone(c),id:cryptoId(),start:v,in:sourceSplit};if(c.speedRamp){left.end=left.start+rampTimelineDuration(left.speedRamp,left.in,left.out);right.end=right.start+rampTimelineDuration(right.speedRamp,right.in,right.out)}t.clips.splice(i,1,left,right);touch(n);return n}
export function removeClip(p,trackId,clipId){const n=cloneProject(p),t=n.tracks.find(x=>x.id===trackId);if(t)t.clips=t.clips.filter(x=>x.id!==clipId);touch(n);return n}
export function addTrack(p,kind='visual'){const n=cloneProject(p),count=n.tracks.filter(t=>t.kind===kind).length+1;n.tracks.push({id:`${kind}-${cryptoId()}`,name:`${kind==='audio'?'Audio':'Video'} ${count}`,kind,clips:[]});touch(n);return n}
export function validateProject(p){const e=[];if(!p||p.version!==PROJECT_VERSION)e.push('Versione progetto non supportata');if(!(p?.width>0&&p?.height>0&&p?.fps>0))e.push('Dimensioni/FPS non validi');for(const t of p?.tracks||[])for(const c of t.clips||[]){if(!(c.end>c.start))e.push(`Durata non valida: ${c.name}`);if(!(c.out>c.in))e.push(`Trim non valido: ${c.name}`);if(!(c.playbackRate>0))e.push(`Playback rate non valido: ${c.name}`);if(c.speedRamp?.schema&&c.speedRamp.schema!=='randstudio.speed-ramp/v1')e.push(`Speed ramp non valido: ${c.name}`);if(c.audio?.schema&&c.audio.schema!=='randstudio.audio/v1')e.push(`Audio spec non valida: ${c.name}`);if(c.track?.schema&&c.track.schema!=='randstudio.track/v1')e.push(`Tracking non valido: ${c.name}`);if(c.mask?.schema&&c.mask.schema!=='randstudio.mask/v1')e.push(`Maschera non valida: ${c.name}`);if(c.kinetic?.schema&&c.kinetic.schema!=='randstudio.kinetic-text/v1')e.push(`Kinetic text non valido: ${c.name}`);if(['text','lower-third','sticker','callout','arrow','light-leak','caption'].includes(c.type)&&!c.graphic)e.push(`Overlay grafico mancante: ${c.name}`)}return e}
function requireClip(p,trackId,clipId){const t=p.tracks.find(x=>x.id===trackId);if(!t)throw new Error(`Track non trovata: ${trackId}`);const c=t.clips.find(x=>x.id===clipId);if(!c)throw new Error(`Clip non trovata: ${clipId}`);return c}function touch(p){p.updatedAt=new Date().toISOString()}function cryptoId(){return globalThis.crypto?.randomUUID?.()||`rs-${Date.now()}-${Math.random().toString(16).slice(2)}`}
