export const PROJECT_VERSION = 1;

export function createProject({ name = 'Nuovo progetto', width = 1920, height = 1080, fps = 30 } = {}) {
  return {version:PROJECT_VERSION,id:cryptoId(),name,width,height,fps,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),tracks:[{id:'video-1',name:'Video 1',kind:'visual',clips:[]},{id:'audio-1',name:'Audio 1',kind:'audio',clips:[]}]};
}
export const cloneProject=p=>structuredClone(p);
export function projectDuration(p){return Math.max(0,...p.tracks.flatMap(t=>t.clips.map(c=>c.end||0)))}
export function addClip(p,trackId,clip){const n=cloneProject(p),t=n.tracks.find(x=>x.id===trackId);if(!t)throw new Error(`Track non trovata: ${trackId}`);const start=Math.max(0,Number(clip.start??projectDuration(n))),duration=Math.max(.05,Number(clip.duration??((clip.out??5)-(clip.in??0))));t.clips.push({id:clip.id||cryptoId(),type:clip.type||(t.kind==='audio'?'audio':'video'),name:clip.name||'Clip',sourceId:clip.sourceId,sourceName:clip.sourceName||clip.name||'media',start,end:start+duration,in:Math.max(0,Number(clip.in??0)),out:Math.max(Number(clip.in??0)+.05,Number(clip.out??duration)),volume:clip.volume??1,opacity:clip.opacity??1,transform:{x:0,y:0,scale:1,rotation:0,...(clip.transform||{})},effects:Array.isArray(clip.effects)?structuredClone(clip.effects):[],keyframes:clip.keyframes?structuredClone(clip.keyframes):{},lutSourceId:clip.lutSourceId,graphic:clip.graphic?structuredClone(clip.graphic):undefined,effectPreset:clip.effectPreset});t.clips.sort((a,b)=>a.start-b.start);touch(n);return n}
export function moveClip(p,trackId,clipId,start){const n=cloneProject(p),c=requireClip(n,trackId,clipId),d=c.end-c.start;c.start=Math.max(0,Number(start));c.end=c.start+d;touch(n);return n}
export function trimClip(p,trackId,clipId,{inPoint,outPoint}){const n=cloneProject(p),c=requireClip(n,trackId,clipId),a=Math.max(0,Number(inPoint??c.in)),b=Math.max(a+.05,Number(outPoint??c.out));c.in=a;c.out=b;c.end=c.start+(b-a);touch(n);return n}
export function splitClip(p,trackId,clipId,time){const n=cloneProject(p),t=n.tracks.find(x=>x.id===trackId);if(!t)throw new Error(`Track non trovata: ${trackId}`);const i=t.clips.findIndex(x=>x.id===clipId);if(i<0)throw new Error(`Clip non trovata: ${clipId}`);const c=t.clips[i],v=Number(time);if(v<=c.start||v>=c.end)return n;const s=c.in+(v-c.start),left={...structuredClone(c),end:v,out:s},right={...structuredClone(c),id:cryptoId(),start:v,in:s};t.clips.splice(i,1,left,right);touch(n);return n}
export function removeClip(p,trackId,clipId){const n=cloneProject(p),t=n.tracks.find(x=>x.id===trackId);if(t)t.clips=t.clips.filter(x=>x.id!==clipId);touch(n);return n}
export function addTrack(p,kind='visual'){const n=cloneProject(p),count=n.tracks.filter(t=>t.kind===kind).length+1;n.tracks.push({id:`${kind}-${cryptoId()}`,name:`${kind==='audio'?'Audio':'Video'} ${count}`,kind,clips:[]});touch(n);return n}
export function validateProject(p){const e=[];if(!p||p.version!==PROJECT_VERSION)e.push('Versione progetto non supportata');if(!(p?.width>0&&p?.height>0&&p?.fps>0))e.push('Dimensioni/FPS non validi');for(const t of p?.tracks||[])for(const c of t.clips||[]){if(!(c.end>c.start))e.push(`Durata non valida: ${c.name}`);if(!(c.out>c.in))e.push(`Trim non valido: ${c.name}`);if(['text','lower-third','sticker','callout','arrow'].includes(c.type)&&!c.graphic)e.push(`Overlay grafico mancante: ${c.name}`)}return e}
function requireClip(p,trackId,clipId){const t=p.tracks.find(x=>x.id===trackId);if(!t)throw new Error(`Track non trovata: ${trackId}`);const c=t.clips.find(x=>x.id===clipId);if(!c)throw new Error(`Clip non trovata: ${clipId}`);return c}function touch(p){p.updatedAt=new Date().toISOString()}function cryptoId(){return globalThis.crypto?.randomUUID?.()||`rs-${Date.now()}-${Math.random().toString(16).slice(2)}`}
