const $=s=>document.querySelector(s);const fileInput=$('#fileInput'),stage=$('#stage'),empty=$('#emptyState'),canvas=$('#imageCanvas'),ctx=canvas.getContext('2d'),video=$('#videoPreview'),videoControls=$('#videoControls'),mediaType=$('#mediaType'),exportBtn=$('#exportBtn'),captureBtn=$('#captureBtn');
const controls={brightness:$('#brightness'),contrast:$('#contrast'),saturation:$('#saturation'),scale:$('#scale')};const outputs={brightness:$('#brightnessOut'),contrast:$('#contrastOut'),saturation:$('#saturationOut'),scale:$('#scaleOut')};let image=null,rotation=0,flipX=1,flipY=1,currentType=null,objectUrl=null;
function state(){return{brightness:+controls.brightness.value,contrast:+controls.contrast.value,saturation:+controls.saturation.value,scale:+controls.scale.value}}
function sync(){for(const k in controls)outputs[k].value=controls[k].value;if(currentType==='image')drawImage();if(currentType==='video')applyVideoFilter()}
function filter(){const s=state();return`brightness(${s.brightness}%) contrast(${s.contrast}%) saturate(${s.saturation}%)`}
function drawImage(){if(!image)return;const rad=rotation*Math.PI/180,swap=Math.abs(rotation)%180===90,w=swap?image.naturalHeight:image.naturalWidth,h=swap?image.naturalWidth:image.naturalHeight;canvas.width=w;canvas.height=h;ctx.save();ctx.clearRect(0,0,w,h);ctx.filter=filter();ctx.translate(w/2,h/2);ctx.rotate(rad);ctx.scale(flipX,flipY);const s=state().scale/100;ctx.scale(s,s);ctx.drawImage(image,-image.naturalWidth/2,-image.naturalHeight/2);ctx.restore()}
function applyVideoFilter(){video.style.filter=filter();video.style.transform=`scale(${state().scale/100}) rotate(${rotation}deg) scaleX(${flipX}) scaleY(${flipY})`}
function cleanup(){if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null}
function loadFile(file){if(!file)return;cleanup();objectUrl=URL.createObjectURL(file);empty.hidden=true;rotation=0;flipX=1;flipY=1;resetControls(false);if(file.type.startsWith('image/')){currentType='image';video.hidden=true;videoControls.hidden=true;canvas.hidden=false;captureBtn.disabled=true;exportBtn.disabled=false;image=new Image();image.onload=drawImage;image.src=objectUrl;mediaType.textContent=`Foto · ${file.name}`}else if(file.type.startsWith('video/')){currentType='video';canvas.hidden=true;video.hidden=false;videoControls.hidden=false;video.src=objectUrl;video.load();captureBtn.disabled=false;exportBtn.disabled=true;mediaType.textContent=`Video · ${file.name}`;applyVideoFilter()}else{alert('Formato non supportato')}}
function resetControls(redraw=true){controls.brightness.value=100;controls.contrast.value=100;controls.saturation.value=100;controls.scale.value=100;rotation=0;flipX=1;flipY=1;if(redraw)sync();else for(const k in controls)outputs[k].value=controls[k].value}
fileInput.addEventListener('change',e=>loadFile(e.target.files[0]));['dragenter','dragover'].forEach(ev=>stage.addEventListener(ev,e=>{e.preventDefault();stage.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>stage.addEventListener(ev,e=>{e.preventDefault();stage.classList.remove('dragover')}));stage.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));Object.values(controls).forEach(c=>c.addEventListener('input',sync));$('#resetBtn').onclick=()=>resetControls();$('#rotateLeft').onclick=()=>{rotation-=90;sync()};$('#rotateRight').onclick=()=>{rotation+=90;sync()};$('#flipX').onclick=()=>{flipX*=-1;sync()};$('#flipY').onclick=()=>{flipY*=-1;sync()};$('#speedSelect').onchange=e=>video.playbackRate=+e.target.value;$('#muteBtn').onclick=e=>{video.muted=!video.muted;e.target.textContent=`Audio: ${video.muted?'OFF':'ON'}`};
const presets={clean:[100,100,100],cinema:[95,115,85],vivid:[105,112,135],bw:[100,115,0]};document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];controls.brightness.value=p[0];controls.contrast.value=p[1];controls.saturation.value=p[2];sync()});$('#dronePreset').onclick=()=>{controls.scale.value=82;controls.contrast.value=108;controls.saturation.value=112;sync()};
exportBtn.onclick=()=>{if(currentType!=='image')return;const a=document.createElement('a');a.download='randstudio-export.png';a.href=canvas.toDataURL('image/png');a.click()};captureBtn.onclick=()=>{if(currentType!=='video'||!video.videoWidth)return;const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;const x=c.getContext('2d');x.filter=filter();x.drawImage(video,0,0);const a=document.createElement('a');a.download='randstudio-frame.png';a.href=c.toDataURL('image/png');a.click()};document.querySelectorAll('.nav').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));btn.classList.add('active');['studio','projects','ai','exports'].forEach(name=>{const el=$(`#${name}Panel`);if(el)el.hidden=name!==btn.dataset.panel})});sync();
